FROM golang:1.24 AS builder

RUN go install go.opentelemetry.io/collector/cmd/builder@latest

WORKDIR /build
COPY builder-config.yaml .
RUN builder --config=builder-config.yaml

FROM ghcr.io/simons-public/distroless/base

WORKDIR /otel
COPY --from=builder /build/otel-collector/otel-collector /usr/bin/otel-collector

EXPOSE 4318

ENTRYPOINT ["/usr/bin/otel-collector", "--config=/etc/otel/collector.yaml"]

LABEL org.opencontainers.image.title="distroless otel-collector"
LABEL org.opencontainers.image.description="distroless otel-collector"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.volumes.config="/etc/otel/collector.yaml"
