version: '3'

vars:
  DESTINATION: ghcr.io/simons-public
  CONTAINERS:
    sh: >
        find . -name Containerfile
        -printf '%h ' 2>/dev/null |
        sed -e 's/\.\///g' | tr '\n' ' '

tasks:
  help:
    desc: Help
    silent: true
    aliases: [default]
    cmds:
    - printf 'Containers꞉ '
    - printf '%s\t' "{{ .CONTAINERS }}"
    - printf '\n\n'
    - task --list

  build:*:*:
    desc: Build image by its name and tag (build:distroless/dotnet:0.1.0)
    vars:
      NAME: '{{ index .MATCH 0 }}'
      TAG: '{{ index .MATCH 1 }}'
    cmds:
    - echo "::group::Build {{.NAME}}:{{.TAG}}"
    - >
      podman build --layers 
      --cache-to ghcr.io/simons-public/podman-cache 
      --cache-from ghcr.io/simons-public/podman-cache
      --build-arg VERSION={{.TAG}}
      -t {{.NAME}}:{{.TAG}} {{.NAME}}/
    - echo "::endgroup::"

  build:*:
    desc: Build image by its name as latest (build:distroless/dotnet)
    vars:
      NAME: '{{ index .MATCH 0 }}'
    cmds:
    - task build:{{.NAME}}:latest

  push:*:*:
    desc: Push an image by its name and tag to $DESTINATION ({{.DESTINATION}})
    vars:
      NAME: '{{ index .MATCH 0 }}'
      TAG: '{{ index .MATCH 1 }}'
    cmds:
    - echo "::group::Push {{.NAME}}:{{.TAG}}"
    - >
      podman tag {{.NAME}}:{{.TAG}}
      {{.DESTINATION}}/{{.NAME}}:{{.TAG}}
    - podman push {{.DESTINATION}}/{{.NAME}}:{{.TAG}}
    - echo "::endgroup::"

  push:*:
    desc: Push an image by its name to $DESTINATION as :latest
    vars:
      NAME: '{{ index .MATCH 0 }}'
    cmds:
    - task push:{{.NAME}}:latest

  lint:
    desc: Lint all Containerfiles
    cmds:
    - >
      find . -name 'Containerfile' -print0 |
      xargs -0 -I{} sh -c
      'echo "Linting {}"; cat "{}" | podman run --rm -i hadolint/hadolint'

  build-all:
    desc: Build all images as :latest
    cmds:
    # build deps first
    - task build:distroless/base build:distroless/dotnet

    # build the rest
    - for: { var: CONTAINERS }
      cmd: |
        case "{{.ITEM}}" in
          distroless/base|distroless/dotnet)
            echo "Skipping {{.ITEM}} (handled already)"
            exit 0
            ;;
        esac
        task build:{{.ITEM}}

  push-all:
    desc: Push all images as :latest
    cmds:
    - for: { var: CONTAINERS }
      cmd: task push:{{.ITEM}}
