FROM archlinux:latest

RUN pacman -Syu --noconfirm \
    bash-completion \
    strace \
    ltrace \
    bind \
    traceroute \
    bpftrace \
    bpftop \
    htop \
    lurk \
    tcpdump \
    mtr \
    systing \
    wget \
    curl \
    && pacman -Scc --noconfirm

CMD bash