FROM archlinux AS builder

ARG ARCH=amd64
ARG AUTHELIA_VERSION=4.39.14
ARG AUTHELIA_TARBALL=authelia-v${AUTHELIA_VERSION}-linux-${ARCH}.tar.gz
ARG GITHUB_URL=https://github.com/authelia/authelia/releases/download

WORKDIR /tmp
RUN curl --location --output authelia.tar.gz \
  "${GITHUB_URL}/v${AUTHELIA_VERSION}/${AUTHELIA_TARBALL}" \
  && tar xzf authelia.tar.gz

FROM distroless
ARG AUTHELIA_VERSION=4.39.14
COPY --from=builder /tmp/authelia /usr/bin/authelia

ENTRYPOINT ["/usr/bin/authelia", "--config", "/etc/authelia.d"]

LABEL org.opencontainers.image.title="distroless authelia"
LABEL org.opencontainers.image.description="distroless authelia"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.volumes.config="/etc/authelia.d"
LABEL build.authelia.version="${AUTHELIA_VERSION}"
