FROM archlinux AS builder

ARG NZBGET_VERSION=25.4
ARG NZBGET_SOURCE=https://github.com/nzbgetcom/nzbget/archive/refs/tags/v${NZBGET_VERSION}.tar.gz

ARG ZLIB_VERSION=1.3.1
ARG ZLIB_SOURCE=https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz

ARG OPENSSL_VERSION=3.3.1
ARG OPENSSL_SOURCE=https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz

ARG LIBXML2_VERSION=2.12.7
ARG LIBXML2_SOURCE=https://download.gnome.org/sources/libxml2/2.12/libxml2-${LIBXML2_VERSION}.tar.xz

ARG BOOST_VERSION=1.90.0
ARG BOOST_SOURCE=https://github.com/boostorg/boost/archive/refs/tags/boost-${BOOST_VERSION}.tar.gz

RUN pacman -Sy --noconfirm \
      base-devel \
      curl \
      perl \
      python \
      unzip \
      cmake \
      git \
      xz

WORKDIR /build/zlib
RUN curl --silent --show-error --location --output zlib.tar.gz \
      ${ZLIB_SOURCE} \
    && tar xf zlib.tar.gz --strip-components=1 \
    && ./configure --prefix=/usr \
    && make -s -j$(nproc) \
    && make install DESTDIR=/base

WORKDIR /build/openssl
RUN curl --silent --show-error --location --output openssl.tar.gz \
      ${OPENSSL_SOURCE} \
    && tar xf openssl.tar.gz --strip-components=1 \
    && ./Configure linux-x86_64 \
         --prefix=/usr \
         --libdir=/usr/lib \
         --with-zlib-include=/base/usr/include \
         --with-zlib-lib=/base/usr/lib \
    && make -s -j$(nproc) \
    && make install_sw DESTDIR=/base

WORKDIR /build/libxml2
RUN curl --silent --show-error --location --output libxml2.tar.xz \
      ${LIBXML2_SOURCE} \
    && tar xf libxml2.tar.xz --strip-components=1 \
    && cmake -S . -B build \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX=/usr \
         -DLIBXML2_WITH_PYTHON=OFF \
         -DLIBXML2_WITH_LZMA=OFF \
         -DLIBXML2_WITH_ICONV=OFF \
         -DLIBXML2_WITH_ZLIB=ON \
         -DZLIB_ROOT=/base/usr \
    && cmake --build build -j$(nproc) \
    && DESTDIR=/base cmake --install build

#WORKDIR /build/boost
#RUN curl --silent --show-error --location --output boost.tar.gz \
#      ${BOOST_SOURCE} \
#    && tar xf boost.tar.gz --strip-components=1 \
#    && ./bootstrap.sh \
#         --prefix=/usr \
#         --with-libraries=filesystem,system,asio,json \
#    && ./b2 \
#         -j$(nproc) \
#         link=shared \
#         runtime-link=shared \
#         threading=multi \
#         variant=release \
#         install \
#         --prefix=/usr \
#         --libdir=/usr/lib \
#         --includedir=/usr/include \
#         --layout=system \
#         --stagedir=/base \
#         install

WORKDIR /build/nzbget
RUN curl --silent --show-error --location --output nzbget.tar.gz \
      ${NZBGET_SOURCE} \
    && tar xf nzbget.tar.gz --strip-components=1 \
    && cmake -S . -B build \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX=/usr \
         -DENABLE_PYTHON=ON \
         -DDISABLE_CURSES=ON \
         -DZLIB_ROOT=/base/usr \
         -DOPENSSL_ROOT_DIR=/base/usr \
    && cmake --build build -j$(nproc) \
    && DESTDIR=/base cmake --install build

RUN rm -fr \
      /base/usr/share/{doc,info,man} \
      /base/usr/lib/pkgconfig \
      /base/usr/lib/cmake

FROM ghcr.io/simons-public/distroless/python

ARG NZBGET_VERSION=25.4

COPY --from=builder /base/usr/lib/ /usr/lib/
COPY --from=builder /base/usr/share/ /usr/share/
COPY --from=builder /base/usr/bin/ /usr/bin/

COPY ./passwd /etc/passwd
COPY ./shadow /etc/shadow

USER nzbget
WORKDIR /var/lib/nzbget

ENTRYPOINT ["nzbget", "-D", "-c", "/etc/nzbget/nzbget.conf"]

LABEL org.opencontainers.image.title="distroless nzbget"
LABEL org.opencontainers.image.description="distroless nzbget"
LABEL org.opencontainers.image.version="0.1.0"
LABEL build.nzbget.version="${NZBGET_VERSION}"
LABEL org.opencontainers.image.volumes.config="/etc/nzbget"
LABEL org.opencontainers.image.volumes.data="/var/lib/nzbget"
