FROM archlinux AS builder

ARG RADARR_VERSION=6.0.4.10291
ARG RADARR_RELEASES=https://github.com/Radarr/Radarr/releases/download/
ARG SQLITE_VERSION=3510000
ARG SQLITE_SOURCE=https://sqlite.org/2025/sqlite-autoconf-${SQLITE_VERSION}.tar.gz

RUN pacman -Sy --noconfirm base-devel

WORKDIR /build/sqlite3
RUN curl --location --output sqlite3.tar.gz ${SQLITE_SOURCE} \
  && tar xf sqlite3.tar.gz --strip-components=1 \
  && ./configure \
       --prefix=/usr \
       --libdir=/usr/lib \
       --enable-fts5 \
       --disable-static \
  && make -j$(nproc) \
  && make install DESTDIR=/base

WORKDIR /extract/radarr
RUN curl --location --output radarr.tar.gz \
      ${RADARR_RELEASES}/v${RADARR_VERSION}/Radarr.master.${RADARR_VERSION}.linux-core-x64.tar.gz \
  && tar xf radarr.tar.gz --strip-components=1

FROM distroless/dotnet
ARG RADARR_VERSION=6.0.4.10291

COPY --from=builder /base/usr/lib/ /usr/lib/
COPY --from=builder /extract/radarr /opt/radarr

COPY ./passwd /etc/passwd
COPY ./shadow /etc/shadow

USER radarr
WORKDIR /var/lib/radarr
ENV HOME=/var/lib/radarr

ENTRYPOINT ["/opt/radarr/Radarr", "-nobrowser", "-data=/var/lib/radarr"]

LABEL org.opencontainers.image.title="distroless radarr"
LABEL org.opencontainers.image.description="distroless radarr"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.volumes.data="/var/lib/radarr"
LABEL build.radarr.version="${RADARR_VERSION}"
