FROM archlinux AS builder

ARG SSHWIFTY_VERSION=0.4.1-beta-release
ARG SSHWIFTY_REPO=https://github.com/nirui/sshwifty

RUN pacman -Sy --noconfirm base-devel icu pcre2 git go npm >/dev/null

WORKDIR /build/sshwifty
COPY ./ui.patch /tmp/ui.patch
RUN git clone ${SSHWIFTY_REPO} . \
  && git checkout ${SSHWIFTY_VERSION} \
  && mv /tmp/ui.patch ./ \
  && git apply ui.patch \
  && npm install >/dev/null \
  && npm run build >/dev/null

FROM scratch
ARG SSHWIFTY_VERSION=0.4.1-beta-release

COPY --from=builder /build/sshwifty/sshwifty /bin/sshwifty
ENV SSHWIFTY_LISTENPORT=8080
EXPOSE 8080

ENTRYPOINT ["/bin/sshwifty"]

LABEL org.opencontainers.image.title="distroless sshwifty"
LABEL org.opencontainers.image.description="distroless sshwifty"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.volumes.data="/var/lib/sshwifty"
LABEL build.sshwifty.version="${SSHWIFTY_VERSION}"
