FROM archlinux AS builder

ARG ARCH=amd64
ARG TRAEFIK_VERSION=3.6.1
ARG TRAEFIK_TARBALL=traefik_v${TRAEFIK_VERSION}_linux_${ARCH}.tar.gz
ARG GITHUB_URL=https://github.com/traefik/traefik/releases/download

WORKDIR /tmp
RUN curl --location --output traefik.tar.gz \
  "${GITHUB_URL}/v${TRAEFIK_VERSION}/${TRAEFIK_TARBALL}" \
  && tar xzf traefik.tar.gz

FROM ghcr.io/simons-public/distroless/base
ARG TRAEFIK_VERSION=3.6.1

COPY --from=builder /tmp/traefik /usr/bin/traefik

ENTRYPOINT ["/usr/bin/traefik", "--configFile=/etc/traefik/traefik.yml"]

LABEL org.opencontainers.image.title="distroless traefik"
LABEL org.opencontainers.image.description="distroless traefik"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.volumes.config="/etc/traefik"
LABEL build.traefik.version="${TRAEFIK_VERSION}"
