FROM archlinux AS builder

ARG VALKEY_VERSION=9.0.0
ARG VALKEY_SOURCES=https://github.com/valkey-io/valkey/archive/refs/tags
ARG ZLIB_VERSION=1.3.1
ARG ZLIB_SOURCE=https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz
ARG OPENSSL_VERSION=3.3.1
ARG OPENSSL_SOURCE=https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz

RUN pacman -Sy --noconfirm base-devel curl perl python busybox

WORKDIR /build/zlib
RUN curl --location --output zlib.tar.gz ${ZLIB_SOURCE} \
  && tar xf zlib.tar.gz --strip-components=1 \
  && ./configure --prefix=/usr \
  && make -j$(nproc) \
  && make install DESTDIR=/base

WORKDIR /build/openssl
RUN curl --location --output openssl.tar.gz ${OPENSSL_SOURCE} \
  && tar xf openssl.tar.gz --strip-components=1 \
  && ./Configure linux-x86_64 \
       --prefix=/usr \
       --libdir=/usr/lib \
       no-tests no-docs \
       --with-zlib-include=/base/usr/include \
       --with-zlib-lib=/base/usr/lib \
  && make -j$(nproc) \
  && make install DESTDIR=/base

WORKDIR /build/valkey
RUN curl --location --output valkey.tar.gz \
      ${VALKEY_SOURCES}/${VALKEY_VERSION}.tar.gz \
  && tar xf valkey.tar.gz --strip-components=1 \
  && make BUILD_TLS=yes USE_SYSTEM_OPENSSL=yes \
        USE_SYSTEMD=no PREFIX=/usr \
        CFLAGS="-I/base/usr/include" \
        LDFLAGS="-L/base/usr/lib" \
        -j$(nproc) \
  && make install INSTALL_BIN=/base/usr/bin

RUN rm -fr \
    /base/usr/share/{doc,info,man} \
    /base/usr/lib/pkgconfig \
    /base/usr/lib/cmake

FROM distroless

ARG VALKEY_VERSION=9.0.0

COPY --from=builder /base/usr/lib/ /usr/lib/
COPY --from=builder /base/usr/share/ /usr/share/
COPY --from=builder /base/usr/bin/ /usr/bin/

COPY ./passwd /etc/passwd
COPY ./shadow /etc/shadow

USER valkey
WORKDIR /var/lib/valkey

ENTRYPOINT ["valkey-server", "/etc/valkey/server.conf"]

LABEL org.opencontainers.image.title="distroless valkey"
LABEL org.opencontainers.image.description="distroless valkey"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.volumes.config="/etc/valkey"
LABEL build.valkey.version="${VALKEY_VERSION}"
